spring:
  datasource:
    master:
      jdbc-url: jdbc:mariadb://localhost:3306/mysql??useUnicode=true&characterEncoding=utf8
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: codb
    slave:
      jdbc-url: jdbc:mariadb://localhost:3306/mysql??useUnicode=true&characterEncoding=utf8
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: codb
spring.main.allow-bean-definition-overriding: true


server:
  port: 8090